### ISSUE TITLE
Implement stats

### ISSUE THREAD

**Issue by horecny** [junaidbhura/fly-dynamic-image-resizer#11]
Hi @junaidbhura , at first great plugin and idea, here are some our future requests, which will be great to implement

**Stats section**
Could you create simple stats section in admin page of plugin, where we will see how many images are currently stored in fly directory, and size of this directory? I developed simple class for this and implemented in our version of your plugin, if you want i can commit it, but its really beta version :)

**Single image stats**
We would like to know, how many images are currently generated (with size information) for selected single image

**Image sizes stats**
It would be very helpful (even i know it from code) to know, what image sizes are currently registered

**Comment by junaidbhura** [comment]
Hey @horecny thanks for raising this issue.

I don't think this will be useful to the vast majority of the users of this plugin. Also, I think it could cause issues on slower servers if there are a lot of images. I'm trying to keep this plugin as light as possible, and easy to extend - so people can build the functionality they need around it.

Because of these reasons, I think I'll close this issue. Sorry about that!
