### ISSUE TITLE
add webp image conversion?

### ISSUE THREAD

**Issue by eimpacteric** [junaidbhura/fly-dynamic-image-resizer#30]
I use Fly Dynamic Image Resizer on ever WP site I build...great job!

Any chance of building webp image conversion into the plugin?

Thanks for your work!

**Comment by junaidbhura** [comment]
Hey @eimpacteric thanks for your kind words!

Unfortunately, this plugin uses WordPress' in-built image converter, rather than its own. So we're kind of at the mercy of what WordPress supports: https://codex.wordpress.org/Uploading_Files

Sorry about that. I'm going to close this issue for now if you don't mind, but please feel free to continue this discussion here!

**Comment by eimpacteric** [comment]
No problem. ;-)

**Comment by luco** [comment]
@ eimpacteric @junaidbhura You can achieve this by using this plugin with webp express, which uses wordpress hooks to create the webp version along the image.
