### ISSUE TITLE
Case sensitive file extension

### ISSUE THREAD

**Issue by junaidbhura** [junaidbhura/fly-dynamic-image-resizer#38]
Originally reported here: https://wordpress.org/support/topic/bug-in-file-extension-capitalization/

Although the file name is the same as the original, the file extension is created using `pathinfo`, which could cause the file extension's case to be different from the original image.

**Comment by dangoodspeed** [comment]
Thanks Junaid, do you need anything else from me?  What is the usual turnaround time for an issue like this?  Just for my own planning as we'll be going live in a week or two with a site that is effected by this bug and I need to know if I have to come up with another solution on my own.

**Comment by junaidbhura** [comment]
Hey @dangoodspeed I can't promise a fix by that time, unfortunately! It is possible, but I'd recommend you finding a solution if you have a site launch that depends on this!

A simple fix would be to just rename the image and upload it again?

**Comment by dangoodspeed** [comment]
Thanks.  In my particular case, it's a site migration with tens of thousands of images, probably several hundred of them with the wrong case.  All the images are already imported, scattered over 15 "years" in the WP uploads folder.  We're using Fly because we didn't want a dozen different image sizes created for each image.  So for me at least, the solution isn't as easy as renaming an image and re-uploading.  I'd have to write a script to change all instances in the database, and also rename all the files with lowercase versions.

**Comment by junaidbhura** [comment]
Wow, that is a lot @dangoodspeed !

Thanks again for raising this issue, and I'll try and roll out a fix as soon as I get some time to spend on this!

**Comment by junaidbhura** [comment]
@dangoodspeed I've updated the plugin with the new fix! Please feel free to continue this discussion here.

**Comment by dangoodspeed** [comment]
Thanks @junaidbhura !   Just tried it and it works!

**Comment by junaidbhura** [comment]
Thanks for the confirmation @dangoodspeed !
