### ISSUE TITLE
TinyPNG Compatibility

### ISSUE THREAD

**Issue by crgeary** [junaidbhura/fly-dynamic-image-resizer#41]
The images uploaded to the Media Library and cropped via the native WordPress `add_image_size()` function are all optimised by the [TinyPNG](https://en-gb.wordpress.org/plugins/tiny-compress-images/) plugin successfully.

However, as far as I can work out, the images created on the fly via this plugin are not optimised. Presumably because it doesn't fire the same actions/filters that WordPress fires when an image is uploaded.

I'm not sure if this is an issue for you, or for the TinyPNG plugin, but I suspect the issue likely exists with other optimisation plugins too, as I assume they all work in the same way.

Is this something you've come across before?

**Comment by junaidbhura** [comment]
Hey @crgeary this plugin comes with a hook `fly_image_created` which can be used to optimize the image: https://github.com/junaidbhura/fly-dynamic-image-resizer/wiki/Actions-&-Filters

Unfortunately, since there are so many image optimization plugins out there, there are no plans to support individual plugins at this point!

Hope that helps! I'm going to close the issue out, but please feel free to continue this conversation.
