### ISSUE TITLE
Adding a dimension bigger than the width of source image generates a file with the incorrect labelled dimension

### ISSUE THREAD

**Issue by filtah** [junaidbhura/fly-dynamic-image-resizer#44]
Hi, Really cool plugin super useful thanks!

One thing I found - for example, I have an image with dimensions 1024 x 768, and I generate an image with a width or height larger than the dimensions, the generated file comes out cropped at the max dimensions, but named with the chosen dimensions.

eg:

 fly_get_attachment_image_src( 2551, [1500, 1000], ['center', 'bottom'] );

generates an image:

/wp-content/uploads/fly-images/2551/image-1500x1000-cb.jpg

indicating it is of size 1500x1000, but the actual dimensions are still 1024 x 768.

It would be awesome if it's possible to allow upscaling the image, or if not, be great to just name it correctly.

Thanks,
Phil

**Comment by junaidbhura** [comment]
Hi @filtah apologies for the delayed response. Since this plugin uses WordPress' core resizing functions, we're kinda forced to work within those constraints.

Changing the file naming system at this time might break backwards compatibility, so I think we can let this one be, since it doesn't really affect anything.

As such, I'm going to close this issue, but please feel free to continue this discussion here!
