### ISSUE TITLE
fly creates thumbs even if the original has smaller size

### ISSUE THREAD

**Issue by joomlabeat** [junaidbhura/fly-dynamic-image-resizer#47]
Hi there,
interesting plugin and I can see some potential on it.
One of the things I noticed is that a new image file with the exact same size as the original will be created when the original image size is smaller than the desired thumb size. 
So, the fly-images folder gets filled with the same size images, but with different naming.

**Comment by junaidbhura** [comment]
Hi @joomlabeat thanks for creating this issue!

This is probably a side-effect of this plugin using core functionality. WordPress does not support "upscaling" images, and since this plugin depends on WordPress for image manipulation, it does not do that either.

This plugin also depends on the name of a file to retrieve the desired size. I think this is just one of those things that we *could* look into solving but would increase the complexity of the plugin.

As such, I don't think I want to touch that bit of the plugin. I'm going to close this issue out at the moment, but please feel free to continue this discussion here, and we could re-open it if needed!
